import React from "react";
export const metadata = {
  title: "EB-3 | About",
  description: "Generated by Next.js",
  keywords: "tienda, online,ecomerce",
};
const AboutPage = () => {
  return (
    <div>
      <h2>AboutPage</h2>
    </div>
  );
};

export default AboutPage;
