import Image from "next/image";

export const metadata = {
  title: "EB-3 | Home",
  description: "Generated by Next.js",
  keywords: "tienda, online,ecomerce",
};
export default function Home() {
  return (
    <>
      <h2>Home page</h2>
    </>
  );
}
